# Basic Functions

In [1]:
import numpy as np
arr1 =np.array([[3,2,5,7,9] , [1,12,3,4,5]])

In [2]:
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
arr1.shape

(2, 5)

In [4]:
arr1.dtype

dtype('int32')

# Give data type Manually to Array

In [5]:
arr2 = np.array([[1,2,3,4.0,5.5] , [6,7,8,9,10]] , dtype = 'int32')

In [6]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Create Blank Arrays

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#  Array Arithmetic

In [11]:
arr1

array([[ 3,  2,  5,  7,  9],
       [ 1, 12,  3,  4,  5]])

In [12]:
arr1*arr1

array([[  9,   4,  25,  49,  81],
       [  1, 144,   9,  16,  25]])

In [13]:
arr1+arr1

array([[ 6,  4, 10, 14, 18],
       [ 2, 24,  6,  8, 10]])

In [14]:
arr1**arr1

array([[        27,          4,       3125,     823543,  387420489],
       [         1, -251658240,         27,        256,       3125]],
      dtype=int32)

In [15]:
12**12

8916100448256

In [16]:
np.array([12 **12])

array([8916100448256], dtype=int64)

In [17]:
np.array([12 **12] , dtype ='int32')

OverflowError: Python int too large to convert to C long

In [18]:
1/arr1

array([[0.33333333, 0.5       , 0.2       , 0.14285714, 0.11111111],
       [1.        , 0.08333333, 0.33333333, 0.25      , 0.2       ]])

# Slicing

In [19]:
arr3 = np.array([5,4,64,4,7,8])

In [20]:
arr4 = arr3[4:6]
arr4

array([7, 8])

In [21]:
arr4[0]=6

In [22]:
arr3

array([ 5,  4, 64,  4,  6,  8])

# To Avoid Above problem , use .copy fn 

In [23]:
arr = np.array([5,4,64,4,7,8])
arr5 = arr[4:6].copy()


In [24]:
arr5

array([7, 8])

In [25]:
arr5[0]=1

In [26]:
arr

array([ 5,  4, 64,  4,  7,  8])

In [27]:
arr1

array([[ 3,  2,  5,  7,  9],
       [ 1, 12,  3,  4,  5]])

In [28]:
arr1[0]

array([3, 2, 5, 7, 9])

In [29]:
arr1[0,4]

9