# Random Sampling with Numpy

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)                                             # Generate random value b/w 0 & 1

array([0.53950174])

In [3]:
np.random.random((3,3))                                         # Generate 3x3 2D array b/w 0 & 1

array([[0.54050259, 0.63691641, 0.09181445],
       [0.82379112, 0.16273417, 0.72661923],
       [0.15510961, 0.83737477, 0.1542783 ]])

In [4]:
np.random.randint(1,4)                                         # Generate random value b/w 1 & 4 

1

In [5]:
np.random.randint(1,4 , (3,3))                                 # Generate 3x3 2D integer array b/w 1 & 4

array([[2, 2, 1],
       [3, 1, 1],
       [1, 1, 2]])

In [6]:
np.random.randint(1,4 , (2,4,4))                                 # Generate 4x4 3D integer array b/w 1 & 4

array([[[3, 3, 3, 3],
        [1, 1, 1, 1],
        [3, 1, 2, 2],
        [1, 3, 3, 2]],

       [[3, 1, 2, 2],
        [3, 2, 1, 1],
        [1, 3, 2, 1],
        [2, 1, 3, 3]]])

But Avove code will generate new array in each run. If we want stable array , Use seed fn  

In [7]:
np.random.seed(10)                                             # Write any value
np.random.randint(1,4 , (3,3))                                 # Generate 3x3 2D integer array b/w 1 &4

array([[2, 2, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [8]:
np.random.seed(10)                                             # After Run 2nd time above array will not change
np.random.randint(1,4 , (3,3))                              

array([[2, 2, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [9]:
2**32-1                                                    # Itne pattern we have , & can generate no.                 

4294967295

# np.random.rand fn()

In [10]:
np.random.rand(3)                                                 # Create 1D random array & values always b/w 0 & 1 

array([0.02517173, 0.70920801, 0.26556613])

In [11]:
np.random.rand(3,3)                                               # Create 1D random array & values always b/w 0 & 1 

array([[0.26360285, 0.15037787, 0.68381843],
       [0.81660184, 0.33607158, 0.89081653],
       [0.19812181, 0.03061665, 0.87761494]])

In [12]:
np.random.randn(3,3)                                             # randn gives +ve & -ve values both

array([[ 0.31085074,  1.72937588, -0.24066194],
       [-1.02735202,  0.42401507,  1.40862087],
       [ 0.43999202, -0.42823439, -0.31201268]])

In [13]:
x = [1,2,3,4,5,6,7,8] 

In [14]:
type(x)

list

In [15]:
np.random.choice(x)

4

In [16]:
for i in range(20):                                               # It gives choices of no. in list
    print(np.random.choice(x))

3
6
6
7
8
7
1
4
5
3
1
2
8
3
1
7
8
1
4
2


In [17]:
np.random.permutation(x)

array([6, 8, 3, 1, 2, 5, 4, 7])

In [18]:
np.random.permutation(x)

array([2, 3, 8, 4, 7, 6, 5, 1])

In [20]:
%%time
np.random.random(4)

Wall time: 0 ns


array([0.87574449, 0.2960687 , 0.13129105, 0.84281793])