In [1]:
import numpy as np

In [2]:
matrix1 = np.array([[1,1,1],[1,1,1],[1,1,1]])                                     # Create 2D array

In [3]:
matrix1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
matrix2 = np.ones((5))                                                           # Create 1D 1's arr
matrix2

array([1., 1., 1., 1., 1.])

In [5]:
matrix2.dtype                                                                     # Check data type 

dtype('float64')

In [6]:
matrix3 = np.ones((3,3))                                             # Create 1's matrix , By default matrix create float arr
matrix3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
matrix4 = np.ones((3,4) , dtype='int32')                             # Create 1's matrix , By give dtype manually Method 1 
matrix4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
matrix4.dtype

dtype('int32')

In [9]:
matrix5 = np.ones((2,3) , dtype=int)                                 # Create 1's matrix , By give dtype manually Method 2

In [10]:
matrix5

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
matrix5.dtype

dtype('int32')

In [12]:
matrix6 = np.zeros((3,4))                                     # Create zeros matrix

In [13]:
matrix6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
matrix7 = np.zeros((3,5) , dtype=bool)                        # Create 3 , 5 zeros array , change dtype float to bool
matrix7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [15]:
matrix8 = np.zeros((3,5) , dtype=str)                        # Create 3 , 5 zeros array , change dtype float to str
matrix8

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

# When we convert float to str ,we get Empty str represent by Quotation mark

In [16]:
matrix9 = np.empty((3,3))
matrix9

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])